#!/usr/bin/env bash
#
# First-boot setup for TestMona on a GCP e2-micro (Always Free tier).
#
#   curl -fsSL https://raw.githubusercontent.com/Mohab9915/testmona/main/deploy/gcp-setup.sh | bash
#
# or clone the repo and run it directly. Safe to re-run: every step checks its
# own state first.
#
# Sized for the free tier: 1 GB RAM, 0.25-2 shared vCPU, 30 GB standard disk.
# The app itself needs ~210 MB; the rest of the headroom exists for the build,
# which is the only genuinely memory-hungry step.
set -euo pipefail

REPO="${REPO:-https://github.com/Mohab9915/testmona.git}"
APP_DIR="${APP_DIR:-$HOME/testmona}"
SWAP_GB="${SWAP_GB:-4}"

log()  { printf '\n\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m !\033[0m %s\n' "$*"; }

# ---------------------------------------------------------------- swap -----
# vite build peaks well above what 1 GB allows. Swap is the difference between
# a slow build and an OOM-killed one, and costs nothing but disk.
if ! swapon --show | grep -q '/swapfile'; then
  log "Creating ${SWAP_GB}GB swap"
  sudo fallocate -l "${SWAP_GB}G" /swapfile
  sudo chmod 600 /swapfile
  sudo mkswap /swapfile >/dev/null
  sudo swapon /swapfile
  grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab >/dev/null
  # A shared-core VM benefits from swapping late rather than eagerly.
  sudo sysctl -w vm.swappiness=10 >/dev/null
  grep -q '^vm.swappiness' /etc/sysctl.conf || echo 'vm.swappiness=10' | sudo tee -a /etc/sysctl.conf >/dev/null
else
  log "Swap already present, skipping"
fi

# -------------------------------------------------------------- docker -----
if ! command -v docker >/dev/null 2>&1; then
  log "Installing Docker"
  sudo apt-get update -qq
  sudo apt-get install -y -qq ca-certificates curl git
  sudo install -m 0755 -d /etc/apt/keyrings
  sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
  sudo chmod a+r /etc/apt/keyrings/docker.asc
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
    | sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
  sudo apt-get update -qq
  sudo apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  sudo usermod -aG docker "$USER"
  # Containers must come back after a reboot without anyone logging in.
  sudo systemctl enable --now docker
else
  log "Docker already installed, skipping"
fi

# ---------------------------------------------------------------- code -----
if [ ! -d "$APP_DIR/.git" ]; then
  log "Cloning $REPO"
  git clone --depth 1 "$REPO" "$APP_DIR"
else
  log "Repo present, pulling latest"
  git -C "$APP_DIR" pull --ff-only
fi
cd "$APP_DIR"

# ----------------------------------------------------------------- env -----
# The compose defaults are development values. Two of them are unsafe on a
# public host: the published placeholder SECRET_KEY (which signs auth tokens
# and encrypts stored integration credentials) and a localhost CORS origin.
if [ ! -f .env ]; then
  log "Writing .env"
  EXTERNAL_IP="$(curl -fsSL -H 'Metadata-Flavor: Google' \
    'http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip' 2>/dev/null || true)"
  ORIGIN="http://${EXTERNAL_IP:-localhost}:3000"

  SECRET="$(openssl rand -base64 48 | tr -d '\n=+/' | cut -c1-48)"

  cat > .env <<EOF
# Generated by deploy/gcp-setup.sh -- do not commit this file.
ENVIRONMENT=production
SECRET_KEY=${SECRET}

DATABASE_URL=sqlite:////app/data/test_management.db

ALLOWED_ORIGINS=${ORIGIN}
VITE_API_URL=/api

# 1 GB of RAM, shared with the OS and Docker. The app needs ~210 MB; these caps
# leave room rather than dividing the box evenly.
BACKEND_MEMORY_LIMIT=640m
FRONTEND_MEMORY_LIMIT=128m
BACKEND_CPUS=1.5
FRONTEND_CPUS=0.5
EOF
  chmod 600 .env
  echo "    ALLOWED_ORIGINS=${ORIGIN}"
else
  log ".env already exists, leaving it alone"
fi

# --------------------------------------------------------------- build -----
log "Building and starting (first build is slow on a shared core - 10-20 min)"
sudo docker compose up -d --build

# -------------------------------------------------------------- backup -----
# The database is ~2 MB. There is no snapshot schedule on the free tier, so a
# local rotated copy is the safety net. Adjust to push to Cloud Storage if you
# want off-box durability.
if ! sudo crontab -l 2>/dev/null | grep -q testmona-backup; then
  log "Installing nightly backup cron"
  sudo mkdir -p /var/backups/testmona
  cat <<'CRON' | sudo tee /usr/local/bin/testmona-backup >/dev/null
#!/usr/bin/env bash
# Nightly SQLite backup. Uses sqlite3 .backup via the container so the copy is
# consistent even mid-write, then prunes anything older than 14 days.
set -euo pipefail
STAMP="$(date +%Y%m%d_%H%M%S)"
DEST="/var/backups/testmona/test_management_${STAMP}.db"
docker compose -f /root/testmona/docker-compose.yml exec -T backend \
  python -c "import sqlite3,sys; s=sqlite3.connect('/app/data/test_management.db'); d=sqlite3.connect('/tmp/backup.db'); s.backup(d); d.close(); s.close()" 2>/dev/null || exit 0
docker compose -f /root/testmona/docker-compose.yml cp backend:/tmp/backup.db "$DEST"
find /var/backups/testmona -name 'test_management_*.db' -mtime +14 -delete
CRON
  sudo sed -i "s#/root/testmona#${APP_DIR}#g" /usr/local/bin/testmona-backup
  sudo chmod +x /usr/local/bin/testmona-backup
  ( sudo crontab -l 2>/dev/null; echo "0 3 * * * /usr/local/bin/testmona-backup # testmona-backup" ) | sudo crontab -
fi

# --------------------------------------------------------------- done ------
log "Waiting for health"
for _ in $(seq 1 60); do
  if curl -fsS --max-time 3 http://localhost:8000/health >/dev/null 2>&1; then break; fi
  sleep 5
done

IP="$(curl -fsSL -H 'Metadata-Flavor: Google' \
  'http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip' 2>/dev/null || echo '<external-ip>')"

echo
sudo docker compose ps
echo
log "TestMona should be reachable at  http://${IP}:3000"
echo
warn "Open the firewall from your workstation or Cloud Shell (not on the VM):"
echo "    gcloud compute firewall-rules create testmona-web \\"
echo "      --allow=tcp:3000 --target-tags=testmona --source-ranges=0.0.0.0/0"
echo "    gcloud compute instances add-tags <INSTANCE> --zone=<ZONE> --tags=testmona"
echo
warn "First visit routes to /setup to create the administrator account."
warn "Traffic is plain HTTP. See deploy/README.md for putting Caddy in front for HTTPS."
